name: "Pull Request"

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          pip install -r dev-requirements.txt 
      - name: PyTest
        run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: '--check --diff --skip-string-normalization --exclude="\.tpl\.py"'